import FifthPage from "./FifthPage/FifthPage";
import FirstPage from "./FirstPage/FirstPage";
import Footer from "./Footer/Footer";
import LastPage from "./LastPage/LastPage";
import Nav from "./Nav";
import SecondPage from "./SecondPage/SecondPage";
import ThirdPage from "./ThirdPage/ThirdPage";
import CardLayout from "./component/Card";
import Head from "next/head";
import { ThemeProvider } from "../Darkmode/ThemeContext";


export default function Home() {
  return (
    <>
      <ThemeProvider>
        <Head>
          <title>Indra Maulana</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className="min-h-screen">
          {/* Navigation */}
          <Nav />
          
          {/* Hero Section */}
          <section className="relative">
            <FirstPage />
          </section>
          
          {/* Skills Cards Section */}
          <section className="relative py-16 md:py-24">
            <CardLayout />
          </section>
          
          {/* Digital Illustration Section */}
          <section className="relative py-16 md:py-24">
            <SecondPage />
          </section>
          
          {/* Visual Design Section */}
          <section className="relative py-16 md:py-24">
            <ThirdPage />
          </section>
          
          {/* Additional Content Section */}
          <section className="relative py-16 md:py-24">
            <FifthPage />
          </section>
          
          {/* Final Section */}
          <section className="relative py-16 md:py-24">
            <LastPage />
          </section>
          
          {/* Footer */}
          <footer className="relative">
            <Footer />
          </footer>
        </div>
      </ThemeProvider>
    </>
  );
}
